<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>181a9551-4464-4a60-9f5b-0fa7ec749e89</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Approval decision where
		the comments is "By default, the decision must be reviewed" , 
		the status is Review ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
