<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>bb3e56a4-159b-4766-bd84-e9a986d6a24a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Very high ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
