<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>7663ea67-05d0-4b84-aab8-f537ba37160a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to approved ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
